apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
  # property-like keys; each key maps to a simple value; actual contents
  mongo-url: mongo-service # Service Name of MongoDB, endpoint