---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongo-secret
  namespace: default
spec:
  encryptedData:
    mongo-password: AgBIIxAPBkXUv4thJhRWxjgx5qBV5yStSXhknTL2ZQb/myl+sraVGX3RJz8PRKaeCPBloeNFpxA1s7Eu9Y2RBXi5G0bM/kAJ7iE4K62F6+EdugyDv6Aw7kWbu+GtGLVeDT6DTeH7p4vNSuOFGQqL473WokiYPqHExPEkC9S8iOAb1lRB4rpO36g6Ct5BvsXFa6gxgBfy4NPy+wueWPXnmcpMiA4Ka4U/qABMO8x8SQmcIAfaL4lu9Y19Zp6uVxbyI8fK66IxRSuNlFeL3CLJKCtIX0kP6hXHNBkGhb2Q2+NoOgOQAcSOPR24feKqZ9M9Jy8jePHeC5MjKQhdARmum0XlP6cIG9ievBB4Q6R5jISl78jpY73lZgjEdhqhkEjjrhkn0IGJ2t3734ukD28tSmww2mu420NcQFuPLRIOo3TFRuhG1hjMrdnJvUhIkCVh/h8aiiVK+2x6gKGjvro3rRPe8Luzus9qa8DtxQIKzRbqqZPENnGQKcVkOaEuH6z04mYPGQLxrfb0GYAuVFFrlH+mFspv27qA7W6VLv2bRw+5AwqVV2mcaJYLos6T9I7m6H7gZsiBlBJzQ94LkykV4tvAxFwqwBa39tL76+jDbhmuqkJkpwQn4yjhPzXxzgureFqLXvcGA4FVfYfFCXSt37Rx8N+lrBw7RfGYXQjdO50WaFZxG7avbjbg1EHwDP+agZOscQ765++shLBgdQWg
    mongo-user: AgCN3dUt3puvSko/FA62S8/yzQGZ3tB7mgMOovoaNC+F1m8oPo5Hobmknzowkml5IYD+TXw3ZQbRQOVb5A2UZYwdIabpTo8nAJq7kSYRpPGlNwLw3LH2u4A5iNxAZIZoMP1FyLxqESFBCbZsKa7sNuu/fsVC+T5LwHB1Abw2XghVunMV9EvaXZDczc3BfxUO7uXEKdQXRlby+0gtBu92YC7LUOYEeF5BSws1Dyr2fyScXW1TllaHM3hfYzcYva/BNcLZuTcqaZmF+vbl5Ct0jKq5EoP5dDc064ozdgB4knkZuG7UiXu9+/s1xetE8lIHRM5miD3Z+IU33xrQEVBK6sQip62qgJoxurtrBh0PNjXN6vUCEEgMvHUxeEaMlp9G7TAvHInexzqFxnLaGsLfs9iu8twu++ywqRzPwra5eVPohKXDM6Q2bm43gKXEHL6JbsvyvhnA8QxEg7nu/3nohOo/Pwr0J7fjmsQtXXrirSvISWrZC750Zh5Z+0hHHWZH72xZQOJhBDrAIZ8vKIql3uRNOVo6nLNY/uGr1U1V4GbumL/HETJWUQJ65vleW5JbFRcasXbMKyr60EAssZA3byRmlPAXXtF9Y0Wkq1F/qglWcItWZPJYHSd2CRNhYrJCJC29BDIWmPGG36ADc1sf+PCA7RVlHrj28iJnxWZYS5Vzniw8PsrB3P+GJyHx8L6x1dzAgEicsEZKdwo=
  template:
    metadata:
      creationTimestamp: null
      name: mongo-secret
      namespace: default
    type: Opaque
